# Jekyll configuration

name: Mo Sharif
title: Mo Sharif
description: Blog

# Url is currently only used only for the RSS feed in feed.xml
url: https://sharif.org
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: ''

author: Mo Sharif
copyright: 2019

share:
  facebook: false
  twitter: true
  gplus: false
  linkedin: true
  pinterest: false
  email: false

social:
  github: Mo4n6
  stackoverflow:
  linkedin: mo-sharif-49b52261
  instagram:
  lastfm:
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key: UA-136763840-1
# Yandex metrica (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica: false


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus:
comments: false

permalink: /:year/:month/:title/

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
